[package]
name = "bevy_tilemap"
version = "0.2.2"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"
description = "Tilemaps with chunks for the Bevy game engine, a simple-driven game engine and app framework"
repository = "https://github.com/joshuajbouw/bevy_tilemap"
license = "MIT"
keywords = ["game", "engine", "bevy", "tiles", "tilemap"]
categories = ["game-engines", "graphics", "gui"]
readme = "README.md"
documentation = "https://docs.rs/bevy_tilemap/latest/bevy_tilemap/"
exclude = ["assets/**/*", ".github/**/*", "doc/**/*"]

[package.metadata.docs.rs]
features = ["serialize", "types"]
default-target = "x86_64-pc-windows-msvc"

[features]
serialize = ["bevy_tilemap_types/serialize", "serde"]
types = []

[workspace]
members = ["library/*", "examples"]

[dependencies]
bevy_app = "0.4"
bevy_asset = "0.5"
bevy_core = "0.4"
bevy_ecs = "0.4"
bevy_math = "0.4"
bevy_render = "0.4"
bevy_reflect = "0.4"
bevy_sprite = "0.4"
bevy_tilemap_types = { path = "library/types" }
bevy_transform = "0.4"
bevy_utils = "0.4"
bitflags = "1.2.1"
hexasphere = { git = "https://github.com/joshuajbouw/hexasphere.git", branch = "fix-1.43" }
serde = { version = "1.0", features = ["derive"], optional = true }
